spring:
  application:
    name: order-service

#circuit breaker
resilience4j:
  retry:
    instances:
      rest-api:
        max-attempts: 3
  circuitbreaker:
    instances:
      rest-circuit-breaker:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3

